---
title: "analysis_jp"
author: "JP Zamanillo"
date: "5/3/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
data <- read_csv("data/Project_Data_final.csv")
data <- na.omit(data) # remove data row w/ NA
inf <- data$X1[is.infinite(data$pop_density_sqmi)]
data <- data[-inf,]
nrow(data)
names(data)
data <- data[,c(3,4,6,9,19,22,23,24,25,27)] # remove redundant variables
# unique(data$Region) 
unique(data$Division) 
head(data)
```

```{r}
data[,-c(3,10)] %>% 
  mutate_at(1:8, list(log = ~ log(.))) ->
  data_log
data_log <- as.data.frame(Map(function(x) replace(x, is.infinite(x), 0), data_log))
data_log <- data_log[,c(9:16)]# only include the logged variables
data_log <- cbind('date'=data$date,'Division'=data$Division,data_log)
# data_log <- cbind('Division'=data$Division,data_log)
data_log <- na.omit(data_log)
names(data_log)
data_log$Division <- as.factor(data_log$Division)
```

```{r}
data_log <- data_log[,c(-7, -10)]
```

```{r}
data_log$median_listing_price_clas <- data$median_listing_price
mlp_mean <- mean(data_log$median_listing_price_clas)
mlp_std <- sd(data_log$median_listing_price_clas)
ifelse(data_log$median_listing_price_clas > mlp_mean+mlp_std, "High",
       ifelse(data_log$median_listing_price_clas < mlp_mean-mlp_std,"Low","Median")) ->
  data_log$median_listing_price_clas
data_log$median_listing_price_clas <- as.numeric(as.factor(data_log$median_listing_price_clas))
head(data_log)
```


```{r}
library(lubridate)
data_log_datesep <- data_log %>% 
  mutate(year = year(date), month = month(date), day = mday(date))
data_log_datesep$month_consec <- 0
for (i in 1:nrow(data_log_datesep)) {
  if (data_log_datesep$year[i] == "2020") {
    data_log_datesep$month_consec[i] <- data_log_datesep$month[i]
  } else if (data_log_datesep$year[i] == "2021") {
    data_log_datesep$month_consec[i] <- (data_log_datesep$month[i] + 12)
  }
}
names(data_log_datesep)
```

```{r}
df <- data_log_datesep %>% 
  select(-date, -median_listing_price_log, -month_consec)
names(df)
```
```{r}
set.seed(123)
train <- sample(nrow(df),0.8*nrow(df))
train_data <- df[train,]
test_data <- df[-train,]
nrow(train_data)
nrow(test_data)
names(train_data)
```

```{r}
library(randomForest)
```


```{r}
set.seed(1)
n_trees <- seq(50, 1000, by = 50)
acc <- c()
for (i in seq(length(n_trees))){
  rf <- randomForest(as.factor(median_listing_price_clas) ~ .,
                     data = train_data, ntree = n_trees[i])
  pred <-  predict(rf, newdata=test_data[-7])
  conf.mat <-  table(test_data[,7], pred)
  TruH <- conf.mat[1,1] # True highs
  TruM <- conf.mat[2,2] # True meds
  TruL <- conf.mat[3,3] # True lows

  FalH <- sum(conf.mat[1,2:3])
  FalM <- sum(conf.mat[2,1], conf.mat[2,3])
  FalL <- sum(conf.mat[3,1:2])
  TotH <- sum(conf.mat[1,])
  TotM <- sum(conf.mat[2,])
  TotL <- sum(conf.mat[3,])
  Tot <-  TotH + TotM + TotL
  Error.Rate <- (FalH + FalM + FalL) / Tot
  Accuracy.Rate <- (TruH + TruM + TruL) / Tot
  acc[i] <- Accuracy.Rate
}
```

```{r}
max(acc)
```

```{r}
plot(n_trees, acc, type = "l")
```

```{r}
set.seed(1)
rf <- randomForest(as.factor(median_listing_price_clas) ~ ., data = train_data,
                   n_tree=100, importance = TRUE)
```

```{r}
pred <-  predict(rf, newdata=test_data[-7])
```

```{r}
conf.mat <-  table(test_data[,7], pred)
conf.mat
```

```{r}
TruH <- conf.mat[1,1] # True highs
TruM <- conf.mat[2,2] # True meds
TruL <- conf.mat[3,3] # True lows
 
FalH <- sum(conf.mat[1,2:3])
FalM <- sum(conf.mat[2,1], conf.mat[2,3])
FalL <- sum(conf.mat[3,1:2])
TotH <- sum(conf.mat[1,])
TotM <- sum(conf.mat[2,])
TotL <- sum(conf.mat[3,])
Tot <-  TotH + TotM + TotL
Error.Rate <- (FalH + FalM + FalL) / Tot
Error.Rate # Check it out
Accuracy.Rate <- (TruH + TruM + TruL) / Tot
Accuracy.Rate # Same as the proportion calculated above 
# Proportion of correct "Highs"
HProp <- TruH / TotH
# Proportion of correct "Mediums"
MProp <- TruM / TotM
# Proportion of correct "Lows"
LProp <- TruL / TotL
# Should I break it up into smaller matrices and find sensitivity and specificity? 
rf.stats <- c(Accuracy.Rate, Error.Rate, HProp, MProp, LProp)
names(rf.stats) <- 
    c("Accuracy Rate", "Error Rate", "Prop of Correct Highs", "Prop of Correct Mediums", "Prop of Correct Lows")
rf.stats

```

```{r}
implplot <- varImpPlot(rf, scale = FALSE)
dotchart(sort(implplot[,1]), xlim=c(0,0.15), xlab="%IncMSE")
```

